### ISSUE TITLE
Require example

### ISSUE THREAD

**Issue by xunto** [itdxer/4DaysORM#12]
Could you please add example on how to require?

Problem is that if you just put catalog "4DaysORM" to PATH. It won't work.

```
> require("4DaysORM.orm.model")
./4DaysORM/orm/model.lua:5: module 'orm.class.global' not found:
	no field package.preload['orm.class.global']
	no file './orm/class/global.lua'
	no file '/usr/share/lua/5.1/orm/class/global.lua'
	no file '/usr/share/lua/5.1/orm/class/global/init.lua'
	no file '/usr/lib/lua/5.1/orm/class/global.lua'
	no file '/usr/lib/lua/5.1/orm/class/global/init.lua'
	no file './orm/class/global.so'
	no file '/usr/lib/lua/5.1/orm/class/global.so'
	no file '/usr/lib/lua/5.1/loadall.so'
	no file './orm.so'
	no file '/usr/lib/lua/5.1/orm.so'
	no file '/usr/lib/lua/5.1/loadall.so'
```
This is a basic way of doing this. Maybe I'll send you a pull request but I want you to explain how do you do it  to exactly know that I won't miss anything.

I'm using lua5.1.

**Comment by itdxer** [comment]
Hi @xunto,
The main module is ``orm``. You need to put just this folder inside of your project

**Comment by xunto** [comment]
@itdxer Oh, right, thanks. Damn, I'm stupid.
