### ISSUE TITLE
Add new Field option "escape_value"

### ISSUE THREAD

**Issue by wesen1** [itdxer/4DaysORM#22]
In my project the varchar values that are inserted into the database may contain special characters that have to be escaped in order to not break the query.

Therefore my idea is to add a new option "escape_value" to the Field class.

LuaSQL provides a method to do this: ````connection:escape(value)````
[See LuaSQL manual](https://keplerproject.github.io/luasql/manual.html)

This method exists for PostgreSQL, MySQL and SQLite3.
Apparently it does not exist for Oracle though.

**Comment by itdxer** [comment]
@wesen1 Unfortunately, I do not support this library anymore, but you can feel free to add PR for this feature. It might be useful for other users.
