### ISSUE TITLE
Table column creation order

### ISSUE THREAD

**Issue by wesen1** [itdxer/4DaysORM#26]
I noticed that the columns are not created in the order in which they are defined.
This is because in lua `arrays have no order`  ([See lua.org](https://www.lua.org/pil/19.3.html))

My idea to fix this is to add a new table configuration option "\_\_columnCreateOrder__". This allows to specify a order of the columns by assigning it a table with the column names (e.g. `{ "columnA", "columnB", "columnC" }`).

I can create a pull request if you are ok with this approach.

**Comment by itdxer** [comment]
It sounds like a good idea 👍
