### ISSUE TITLE
Many to Many Relationship

### ISSUE THREAD

**Issue by AzureusNation** [itdxer/4DaysORM#6]
@itdxer 

Is it possible to do a many to many relationship?

The only thing I can think of from the documentation is creating a separate table that has the 2 models foreign keys and join them together with the primary key.

I haven't tested this but it makes sense to use the join method with the model.id?

Any help would be appreciated as I'm using this for garry's mod.

**Comment by itdxer** [comment]
@AzureusNation

There is no methods or functionality that can help you work with many to many relations. But you are right that it is possible to create additional table that stores many to many relations between other two tables. And of course, you need to make all joins by your own if you need to get information using this relations.

```
local User = Table({
    __tablename__ = "user",
    name = fields.CharField({max_length = 100, unique = false, null = false}),
})
local Post = Table({
    __tablename__ = "post",
    name = fields.CharField({max_length = 100, unique = false, null = false}),
})
local Likes = Table({
    __tablename__ = "likes",
    user_id = fields.ForeignKey({to = User}),
    post_id = fields.ForeignKey({to = Post})
})
```

I have used this library a long time ago and I forgot the right way to build queries. The main idea was simple. All methods sequence just add a specific instruction in query builder. So the finallquery should be something like this:

```
local all_likes = Likes.get:left_join(User):left_join(Post):all()
```

Hope it helps.

**Comment by AzureusNation** [comment]
@itdxer 

Thanks for this and also what do the different join types mean? (left, right, full and another that slips my mind).

**Comment by itdxer** [comment]
It's a different join types in SQL.
left_join - LEFT JOIN
right_join - RIGHT JOIN
and so on...

Some rules you can find here

![Visual SQL JOINS](http://blog.bados.org.ua/wp-content/uploads/2014/11/Visual_SQL_JOINS.jpg)
