### ISSUE TITLE
luasql execute maybe mysql has gone away

### ISSUE THREAD

**Issue by mycoco2014** [itdxer/4DaysORM#9]
local break_conn = string.find(err, "LuaSQL%:%serror%sexecuting%squery%.%sMySQL%:%sMySQL%sserver%shas%sgone%saway")
            if break_conn then
                assert(false, tostring(err))
            end
            return nil

**Comment by itdxer** [comment]
Hi @mycoco2014,
Could you please your problem in more details?

**Comment by mycoco2014** [comment]
when connect mysql ,maybe disconnection , need check mysql error string , you can see luasql lib in github
